title: DanM
subtitle: Data Engineer, Hacker, Caffeine Enthusiast
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    # - text: Blog
    #   url: /blog
    # - text: Contact
    #   url : /contact


# Edit Author details (For multi authors check _data/authors.yml)
author_logo: my_profile.png
author: Dan Massarano
author_bio:
    Data Engineer by day, wannabe hacker by night. I like learning new things and either making or breaking stuff is my favourite way to do it.
author_email: "danielmassarano@gmail.com"
author_location: Manchester, UK
author_website_url: "https://danmassarano.com"
typewrite-text:
    I'm a data engineer and I'm interested in big data, security, and automation
hero_cover_img: sample_cover.jpg

# Experiences
author_work_experiences:
            - company_name: The Data Shed
              company_logo: the_data_shed.png
              company_url: https://thedatashed.co.uk/
              designation: Senior Data Engineer
              description: Tech lead for a team working on GCP migration that builds, tests, and deploys big data solutions.
              visibility: true
            - company_name: KPMG UK
              company_logo: kpmg.jpg
              company_url: https://home.kpmg/uk/en/home.html
              designation: Data Engineer
              description: Developed data solutions to automate business processes and aid reporting for business-critical applications. Designed data architecture and created ETL pipelines in ADF and SSIS.
              visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: false

# Education
author_education_details:
              - college_logo: university_of_manchester.jpg
                college_name: The University of Manchester
                college_url: https://www.manchester.ac.uk/
                college_degree: Computer Science
                description: Bachelor of Science (Hons)
                visibility: true

# Certifications
author_certification_details:
              - organisation_logo: google.jpg
                issuing_org: Google
                cartification_name: Google Cloud Certified Associate Cloud Engineer
                issue_date: Jul 2022
                verify_url: https://www.credential.net/18ce7dc0-a7dc-4707-8733-d71053b46d02
                visibility: true
              - organisation_logo: google.jpg
                issuing_org: Google
                cartification_name: Google Cloud Certified Cloud Digital Leader
                issue_date: Nov 2021
                verify_url: https://www.credential.net/2d924198-4dbe-4be9-b2c1-1cce51a267ec
                visibility: true
              - organisation_logo: microsoft.jpg
                issuing_org: Microsoft
                cartification_name: "Microsoft Certified: Azure Data Engineer Associate"
                issue_date: Dec 2020
                verify_url: https://www.youracclaim.com/badges/63ba3ba5-a0d4-4964-8e3d-1e592904d1be
                visibility: true
              - organisation_logo: microsoft.jpg
                issuing_org: Microsoft
                cartification_name: "Microsoft Certified: Azure Data Fundamentals"
                issue_date: Aug 2020
                verify_url: https://www.youracclaim.com/badges/1410afa3-c7f8-4433-bbe5-73b5778a8eaa
                visibility: true
              - organisation_logo: microsoft.jpg
                issuing_org: Microsoft
                cartification_name: "Microsoft Certified: Azure Security Fundamentals"
                issue_date: Jan 2023
                verify_url: https://www.youracclaim.com/badges/1410afa3-c7f8-4433-bbe5-73b5778a8eaa
                visibility: false
              - organisation_logo: microsoft.jpg
                issuing_org: Microsoft
                cartification_name: "Microsoft Certified: Azure Fundamentals"
                issue_date: Mar 2020
                verify_url: https://www.youracclaim.com/badges/739dc1e5-8711-4f72-a95e-404614f301f0
                visibility: true
              - organisation_logo: aws.jpg
                issuing_org: Amazon Web Services (AWS)
                cartification_name: AWS Certified Cloud Practitioner
                issue_date: Dec 2019
                verify_url: https://www.youracclaim.com/badges/03d1308f-da29-4b78-8107-280993eeb5b4
                visibility: true
              - organisation_logo: hashicorp.jpg
                issuing_org: HashiCorp
                cartification_name: "HashiCorp Certified: Terraform Associate"
                issue_date: May 2022
                verify_url: https://www.credly.com/badges/1695833c-e63d-447c-8c94-5071ff348bef
                visibility: true
              - organisation_logo: scrum_org.jpg
                issuing_org: Scrum.org
                cartification_name: Professional Scrum Master™ I (PSM I)
                issue_date: Jul 2021
                verify_url: https://www.credly.com/badges/5fb02a6f-d270-42f7-9ee7-36c403ea84ee
                visibility: true
              - organisation_logo: axelos.jpg
                issuing_org: AXELOS Global Best Practice
                cartification_name: ITIL Foundation
                issue_date: Dec 2018
                verify_url: https://www.youracclaim.com/badges/d3c5348a-989e-4e36-b9ea-93795b3bf2a6
                visibility: true

# social links
twitter_username: danmassarano
github_username:  danmassarano
linkedin_username: dmassarano
instagram_username: purpl3d0ll

# mailchimp embedded form url (newsletter):
# mailchimp_form_url:

# contact form - (choose formspress or getform)
# getform_endpoint:
# formspree_email:

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show
show_author_work_experiences: true
show_author_project_details: false
show_author_education_details: true
show_author_certification_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
